# Generated by Django 5.1.1 on 2024-12-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddBooks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=100)),
                ("ISBN", models.IntegerField()),
                ("Quantity", models.IntegerField()),
                ("Author", models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name="IssueBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Student_name", models.CharField(max_length=100)),
                ("Student_roll", models.IntegerField()),
                ("Student_branch", models.CharField(max_length=100)),
                ("book_name", models.CharField(max_length=100)),
                ("ISBN", models.IntegerField()),
                ("Issue_date", models.DateField()),
            ],
        ),
    ]
